development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:268046f4956aa30a6ee29614bcda8a4f@hammerjaw.redistogo.com:9606/
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: action-cable-example-two_production
